name: Github Workflow CI/CD
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
        node-version: ${{ matrix.node-version }}

      - name: GitHub Action for Yarn  
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install   
           
      - name: Creating build 
        run: yarn build

      - name: installing surge
        run: npm install -g surge

        
      - name: Deploying using surge
        run: surge ./build https://hrpwaet.surge.sh/ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
